title: Industrial ML Experts
baseURL: /
params:
  footer:
    content: '&copy; Manikandan Selvanathan. All rights reserved.'
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: /images/logo.png
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: ''
  header:
    has_nav: true
    logo_img: /images/logo.png
    title: IndustrialMLExperts
    menu:
      actions:
        - label: Github
          url: /githubpage
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
